#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: make
#
Name     : latencytop
Version  : 0.4
Release  : 14
URL      : http://localhost/cgit/projects/latencytop/snapshot/latencytop-0.4.tar.bz2
Source0  : http://localhost/cgit/projects/latencytop/snapshot/latencytop-0.4.tar.bz2
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: latencytop-bin = %{version}-%{release}
Requires: latencytop-data = %{version}-%{release}
BuildRequires : glib-dev
BuildRequires : gtk+-dev
BuildRequires : pkgconfig(ncursesw)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}
Patch1: build.patch

%description
No detailed description available

%package bin
Summary: bin components for the latencytop package.
Group: Binaries
Requires: latencytop-data = %{version}-%{release}

%description bin
bin components for the latencytop package.


%package data
Summary: data components for the latencytop package.
Group: Data

%description data
data components for the latencytop package.


%prep
%setup -q -n latencytop-0.4
cd %{_builddir}/latencytop-0.4
%patch -P 1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1689788865
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
pushd src
make  %{?_smp_mflags}
popd


%install
export SOURCE_DATE_EPOCH=1689788865
rm -rf %{buildroot}
pushd src
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/latencytop

%files data
%defattr(-,root,root,-)
/usr/share/latencytop/latencytop.trans
