#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : latencytop
Version  : 0.4
Release  : 11
URL      : http://localhost/cgit/projects/latencytop/snapshot/latencytop-0.4.tar.bz2
Source0  : http://localhost/cgit/projects/latencytop/snapshot/latencytop-0.4.tar.bz2
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: latencytop-bin
Requires: latencytop-data
BuildRequires : glib-dev
BuildRequires : gtk+-dev
BuildRequires : pkgconfig(ncursesw)
Patch1: build.patch

%description
No detailed description available

%package bin
Summary: bin components for the latencytop package.
Group: Binaries
Requires: latencytop-data

%description bin
bin components for the latencytop package.


%package data
Summary: data components for the latencytop package.
Group: Data

%description data
data components for the latencytop package.


%prep
%setup -q -n latencytop-0.4
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1510693239
pushd src
make V=1  %{?_smp_mflags}
popd

%install
export SOURCE_DATE_EPOCH=1510693239
rm -rf %{buildroot}
pushd src
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/latencytop

%files data
%defattr(-,root,root,-)
/usr/share/latencytop/latencytop.trans
